language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install numpy quantities
  - pip install pytest pyaml coverage codecov
  - python setup.py install
script:
  - py.test
after_success:
  - codecov
